/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.JTextField;
/**
 *
 * @author mohammedhamdy32
 */
public class Admain extends javax.swing.JFrame {

    /**
     * Creates new form Admain
     */
    int aq=0;
    public static  int x=0;

    public Admain() {
        initComponents();
         jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            jLabel8.setVisible(false);
            jLabel9.setVisible(false);
            jLabel10.setVisible(false);
            jLabel11.setVisible(false);
            jLabel12.setVisible(false);
            jLabel13.setVisible(false);
            jLabel14.setVisible(false);
            jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            jLabel17.setVisible(false);
            jLabel18.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);
            jTextField8.setVisible(false);
            jTextField9.setVisible(false);
            jTextField10.setVisible(false);
            jTextField11.setVisible(false);
            jTextField12.setVisible(false);
            jTextField13.setVisible(false);
            jTextField14.setVisible(false);
            jTextField15.setVisible(false);
            jTextField16.setVisible(false);
            jLabel19.setVisible(false);
            jLabel20.setVisible(false);
            jLabel21.setVisible(false);
            jLabel22.setVisible(false);
            jLabel23.setVisible(false);
            jLabel24.setVisible(false);
            jLabel25.setVisible(false);
            jLabel26.setVisible(false);
            jLabel27.setVisible(false);
            jLabel28.setVisible(false);
            jLabel29.setVisible(false);
            jLabel30.setVisible(false);
            jLabel31.setVisible(false);
            jLabel32.setVisible(false);
            jTextField17.setVisible(false);
            jTextField18.setVisible(false);
            jTextField19.setVisible(false);
            jTextField20.setVisible(false);
            jTextField21.setVisible(false);
            jTextField22.setVisible(false);
            jTextField23.setVisible(false);
            jTextField24.setVisible(false);
            jTextField25.setVisible(false);
            jTextField26.setVisible(false);
            jTextField27.setVisible(false);
            jTextField28.setVisible(false);
            jTextField29.setVisible(false);
            jTextField30.setVisible(false);
            jTextField31.setVisible(false);
            
//        
//        if(!jRadioButton1.isSelected())
//        {
////            jLabel1.setVisible(false);
////            jLabel2.setVisible(false);
////            jLabel3.setVisible(false);
////            jLabel4.setVisible(false);
////            jLabel5.setVisible(false);
////            jLabel6.setVisible(false);
////            jTextField1.setVisible(false);
////            jTextField2.setVisible(false);
////            jTextField3.setVisible(false);
////            jRadioButton1.setVisible(false);
////            jRadioButton2.setVisible(false);
////            jButton1.setVisible(false);
////            jComboBox.setVisible(false);
////            jLabel7.setText("No availabe trip ");
//        }
 Scanner istream=null;
        try {
           
           istream=new Scanner(new File("open2.txt")); 
             x= istream.nextInt();
        }
        catch(IOException e){}
      
        if(x==1)
        {
            jRadioButton1.doClick();
        }
        istream.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setText("Admin Panal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("How many TextField you want");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 214, -1));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 120, 141, -1));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 330, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 330, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 330, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 330, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 330, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 330, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 330, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 330, -1));
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, 330, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, 330, -1));
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 330, -1));
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 330, -1));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 330, -1));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 330, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("name of textfield number 1");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("name of textfield number 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 160, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("name of textfield number 3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("name of textfield number 4");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("name of textfield number 5");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("name of textfield number 6");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("name of textfield number 7");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("name of textfield number 8");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 220, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("name of textfield number 9");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 220, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("name of textfield number 10");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 220, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("name of textfield number 11");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 220, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("name of textfield number 12");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 220, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("name of textfield number 13");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 220, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("name of textfield number 14");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 220, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("name of textfield number 15");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 220, -1));

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 730, 330, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("name of textfield number 16");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, 180, -1));
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 180, 330, -1));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 220, 330, -1));
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 330, -1));
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 300, 330, -1));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 340, 330, -1));

        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 330, -1));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 420, 330, -1));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 330, -1));
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 500, 330, -1));
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 540, 330, -1));
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 580, 330, -1));
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 330, -1));
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 660, 330, -1));
        getContentPane().add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 700, 330, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("name of textfield number 17");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("name of textfield number 18");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 260, 180, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("name of textfield number 19");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 180, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("name of textfield number 20");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 340, 180, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("name of textfield number 21");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, 180, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("name of textfield number 22");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 180, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("name of textfield number 23");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, 180, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("name of textfield number 24");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 500, 180, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("name of textfield number 25");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 180, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("name of textfield number 26");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 180, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 0, 0));
        jLabel29.setText("name of textfield number 27");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 180, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 0));
        jLabel30.setText("name of textfield number 28");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, 180, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 0));
        jLabel31.setText("name of textfield number 29");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 700, 180, -1));
        getContentPane().add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 740, 330, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("name of textfield number 30");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 740, 180, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 120, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 120, -1, -1));
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jRadioButton1.setText("open form");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 120, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin Home.png"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        int a =JOptionPane.showConfirmDialog(null, "are you sure you want to exit ","Warning",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try
        {

            aq =Integer.parseInt(jTextField1.getText());
            if( aq>30){
                JOptionPane.showMessageDialog(null, "NUMBER OF TEXT BOX MUST BE FROM 1 TO 30");
            }
            else
            {
                switch (aq){
                    case 0 ->
                    {
                        
                    }
                    case 1 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                    }
                    case 2 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                    }
                    case 3 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                    }
                    case 4 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                    }
                    case 5 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                    }
                    case 6 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);

                    }
                    case 7 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                    }
                    case 8 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                    }
                    case 9 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                    }
                    case 10 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                    }
                    case 11 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                    }
                    case 12 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                    }
                    case 13 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                    }
                    case 14 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                    }
                    case 15 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                    }
                    case 16 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 17 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 18 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 19 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 20 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 21 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 22 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 23 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 24 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 25 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 26 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel28.setVisible(true);
                        jTextField27.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 27 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel28.setVisible(true);
                        jTextField27.setVisible(true);
                        jLabel29.setVisible(true);
                        jTextField28.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 28 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel28.setVisible(true);
                        jTextField27.setVisible(true);
                        jLabel29.setVisible(true);
                        jTextField28.setVisible(true);
                        jLabel30.setVisible(true);
                        jTextField29.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 29 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel28.setVisible(true);
                        jTextField27.setVisible(true);
                        jLabel29.setVisible(true);
                        jTextField28.setVisible(true);
                        jLabel30.setVisible(true);
                        jTextField29.setVisible(true);
                        jLabel31.setVisible(true);
                        jTextField30.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                    case 30 ->                     {
                        jLabel4.setVisible(true);
                        jTextField2.setVisible(true);
                        jLabel5.setVisible(true);
                        jTextField3.setVisible(true);
                        jLabel6.setVisible(true);
                        jTextField4.setVisible(true);
                        jLabel7.setVisible(true);
                        jTextField5.setVisible(true);
                        jLabel8.setVisible(true);
                        jTextField6.setVisible(true);
                        jLabel9.setVisible(true);
                        jTextField7.setVisible(true);
                        jLabel10.setVisible(true);
                        jTextField8.setVisible(true);
                        jLabel11.setVisible(true);
                        jTextField9.setVisible(true);
                        jLabel12.setVisible(true);
                        jTextField10.setVisible(true);
                        jLabel13.setVisible(true);
                        jTextField11.setVisible(true);
                        jLabel14.setVisible(true);
                        jTextField12.setVisible(true);
                        jLabel15.setVisible(true);
                        jTextField13.setVisible(true);
                        jLabel16.setVisible(true);
                        jTextField14.setVisible(true);
                        jLabel17.setVisible(true);
                        jTextField15.setVisible(true);
                        jLabel18.setVisible(true);
                        jTextField16.setVisible(true);
                        jLabel19.setVisible(true);
                        jTextField18.setVisible(true);
                        jLabel20.setVisible(true);
                        jTextField19.setVisible(true);
                        jLabel21.setVisible(true);
                        jTextField20.setVisible(true);
                        jLabel22.setVisible(true);
                        jTextField21.setVisible(true);
                        jLabel23.setVisible(true);
                        jTextField22.setVisible(true);
                        jLabel24.setVisible(true);
                        jTextField23.setVisible(true);
                        jLabel25.setVisible(true);
                        jTextField24.setVisible(true);
                        jLabel26.setVisible(true);
                        jTextField25.setVisible(true);
                        jLabel27.setVisible(true);
                        jTextField26.setVisible(true);
                        jLabel28.setVisible(true);
                        jTextField27.setVisible(true);
                        jLabel29.setVisible(true);
                        jTextField28.setVisible(true);
                        jLabel30.setVisible(true);
                        jTextField29.setVisible(true);
                        jLabel31.setVisible(true);
                        jTextField30.setVisible(true);
                        jLabel32.setVisible(true);
                        jTextField31.setVisible(true);
                        jLabel3.setVisible(true);
                        jTextField17.setVisible(true);
                    }
                }
            }

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,"you must enter numbers only");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel3.setVisible(false);
        jTextField17.setVisible(true);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        jLabel14.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jTextField7.setVisible(false);
        jTextField8.setVisible(false);
        jTextField9.setVisible(false);
        jTextField10.setVisible(false);
        jTextField11.setVisible(false);
        jTextField12.setVisible(false);
        jTextField13.setVisible(false);
        jTextField14.setVisible(false);
        jTextField15.setVisible(false);
        jTextField16.setVisible(false);
        jLabel19.setVisible(false);
        jLabel20.setVisible(false);
        jLabel21.setVisible(false);
        jLabel22.setVisible(false);
        jLabel23.setVisible(false);
        jLabel24.setVisible(false);
        jLabel25.setVisible(false);
        jLabel26.setVisible(false);
        jLabel27.setVisible(false);
        jLabel28.setVisible(false);
        jLabel29.setVisible(false);
        jLabel30.setVisible(false);
        jLabel31.setVisible(false);
        jLabel32.setVisible(false);
        jTextField17.setVisible(false);
        jTextField18.setVisible(false);
        jTextField19.setVisible(false);
        jTextField20.setVisible(false);
        jTextField21.setVisible(false);
        jTextField22.setVisible(false);
        jTextField23.setVisible(false);
        jTextField24.setVisible(false);
        jTextField25.setVisible(false);
        jTextField26.setVisible(false);
        jTextField27.setVisible(false);
        jTextField28.setVisible(false);
        jTextField29.setVisible(false);
        jTextField30.setVisible(false);
        jTextField31.setVisible(false);
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField18.setText("");
        jTextField19.setText("");
        jTextField20.setText("");
        jTextField21.setText("");
        jTextField22.setText("");
        jTextField23.setText("");
        jTextField24.setText("");
        jTextField25.setText("");
        jTextField26.setText("");
        jTextField27.setText("");
        jTextField28.setText("");
        jTextField29.setText("");
        jTextField30.setText("");
        jTextField31.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try
        {
            if(Integer.parseInt(jTextField1.getText())<=30&&Integer.parseInt(jTextField1.getText())!=0&&!jTextField2.getText().equals("")){

                FileWriter b = new FileWriter("data.txt");
                PrintWriter f= new PrintWriter(b);
                
                f.println(aq);
                
                f.println(jTextField2.getText());
                f.println(jTextField3.getText());
                f.println(jTextField4.getText());
                f.println(jTextField5.getText());
                f.println(jTextField6.getText());
                f.println(jTextField7.getText());
                f.println(jTextField8.getText());
                f.println(jTextField9.getText());
                f.println(jTextField10.getText());
                f.println(jTextField11.getText());
                f.println(jTextField12.getText());
                f.println(jTextField13.getText());
                f.println(jTextField14.getText());
                f.println(jTextField15.getText());
                f.println(jTextField16.getText());
                f.println(jTextField17.getText());
                f.println(jTextField18.getText());
                f.println(jTextField19.getText());
                f.println(jTextField20.getText());
                f.println(jTextField21.getText());
                f.println(jTextField22.getText());
                f.println(jTextField23.getText());
                f.println(jTextField24.getText());
                f.println(jTextField25.getText());
                f.println(jTextField26.getText());
                f.println(jTextField27.getText());
                f.println(jTextField28.getText());
                f.println(jTextField29.getText());
                f.println(jTextField30.getText());
                f.println(jTextField31.getText());
                JOptionPane.showMessageDialog(null, " data is successfuly saved ");
                f.close();
                setVisible(false);
                new Admain().setVisible(true);
                       
            }
            else
            {
                JOptionPane.showMessageDialog(null, " you must enter values first befor you can save the data");
            }
        }

        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
          PrintWriter open =null;
        try{
            open =new PrintWriter(new FileWriter("open2.txt"));
        }
        catch(Exception e){}
        //open.print("1");
        if(jRadioButton1.isSelected())
        open.print("1");
        else if(!jRadioButton1.isSelected())
        open.print("0");
        open.close();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
