/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author mohammedhamdy32
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import sun.misc.Unsafe;
//import javafx.application;.Application;
public class Vote extends javax.swing.JFrame {

    /**
     * Creates new form Vote
     */
    
        Connection conn=null;
     PreparedStatement pb;
      //int t=dbjframe.t;
     Separate_items sp=new Separate_items();
    public Vote() {
        
        initComponents();      
        boolean b;
        FileItems f1=new FileItems();
        b=f1.get_state_open_or_close();
        String s=f1.get_items();
        jTextArea1.setText(s);
       jList1.setListData(sp.get_Items(s));
       if(b==true)
           jRadioButton1.doClick();
       // System.out.println("t="+dbjframe.t);
       if(dbjframe.t==1)
       {
           if(b==false)
           {
               jList1.setVisible(false);
               jButton2.setVisible(false);
               jLabel1.setText("NO vote is present");
              
           }
           jRadioButton1.setVisible(false);
           jRadioButton2.setVisible(false);
           jTextArea1.setVisible(false);
           jButton1.setVisible(false);
           jLabel2.setVisible(false);
           jTextArea2.setVisible(false);
           jLabel6.setVisible(false);
       }
       conn=  dbt.Connecdb();
       jLabel5.setText(f1.get_text_area());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 204, 316));

        jButton1.setText("save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 164, 82, -1));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("open vote");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 164, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("multichoise");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 192, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 49, 268, 95));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Vote");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 86, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 680, 71));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("write items separated  by commas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 260, 29));

        jButton3.setText("Display persents");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 226, 131, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setText("Clear your vote");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 140, 30));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 60));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 90));

        jLabel6.setText("Write details about the vote");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 160, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/431539-PE9O1K-661-1140x684.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -60, 1080, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(jRadioButton2.isSelected())
       {
           jList1.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
          // System.out.println("sdfghj");   
       }
       else
         jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
         
       
       FileItems f2=new FileItems();
               
       if(jRadioButton1.isSelected())
           f2.set_state_open_or_close(true);
       else            f2.set_state_open_or_close(false);

           
       
       String s3=jTextArea1.getText();
       f2.set_items(s3);
       Separate_items sp2 =new Separate_items();
       jList1.setListData( sp2.get_Items(s3));
       try{
        PreparedStatement select3 =conn.prepareStatement("UPDATE account_admin set vote=0 , voteIndex=0");
        select3.executeUpdate();

       }catch(Exception e)
       {
           System.out.println(e);
       }
       
       f2.set_text_area(jTextArea2.getText());
       jLabel5.setText(jTextArea2.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try {
            PreparedStatement select =conn.prepareStatement("SELECT vote FROM `account_admin` WHERE (name)=(?)");
            select.setString(1,dbjframe.name);
             ResultSet res =select.executeQuery();
              if(res.next())
              {
                 // System.out.println(res.getString(1));
                  if(Integer.parseInt(res.getString(1))==1)
                  jLabel1.setText("you have votted already");
                  else
                  {
         
          PreparedStatement select2 =conn.prepareStatement("UPDATE account_admin set vote=1,voteIndex=? WHERE (name)=(?)");
          select2.setString(1, jList1.getSelectedIndex()+1+"");
          select2.setString(2 , dbjframe.name);
          select2.executeUpdate();
                 JOptionPane.showMessageDialog(this, "You vote was saved");
                  }
                      
              }
            } catch (SQLException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           int []idex=new int[sp.size_of_list];
        try {
                PreparedStatement select4 =conn.prepareStatement("SELECT voteIndex FROM `account_admin`");
                ResultSet res =select4.executeQuery();
             while(res.next())
              {
             
                  for(int i=0;i<sp.size_of_list;i++)
                if(res.getInt(1)==i+1)
                 { 
                     idex[i]++;    
                    break;}
              }
             //System.out.println("the number of votes for idex 0="+idex[0]+"the number of votes for idex 0="+idex[1]+"the number of votes for idex 0="+idex[2]);
            } catch (SQLException ex) {
                Logger.getLogger(Vote.class.getName()).log(Level.SEVERE, null, ex);
            }
        
            PieChart cc=new PieChart("Pir chart", "Pie Chart for votting",sp.array_of_list,idex,sp.size_of_list);
            cc.pack();
            cc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            cc.setVisible(true);
            String textItems="";
            for(int i=0;i<sp.size_of_list ;i++)
                textItems=textItems+sp.array_of_list[i]+"="+idex[i]+" , ";
            
            jLabel1.setText(textItems);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         try{ PreparedStatement select2 =conn.prepareStatement("UPDATE account_admin set vote=0,voteIndex=0 WHERE (name)=(?)");
          select2.setString(1 , dbjframe.name);
          select2.executeUpdate();
          jLabel1.setText("");
          JOptionPane.showMessageDialog(this, "your vote was removed");
          
         }catch(Exception e)
         {
             System.out.println(e);
         }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
